version: '2.0'
services:
  web:
    container_name: bet-web
    restart: always
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/htdocs:/var/www/htdocs
    privileged: true
  mysql:
    image: mysql:5.6.49
    container_name: bet-mysql
    restart: always
    environment:
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=sportsbetpwd
      - MYSQL_DATABASE=sportsbet
      - MYSQL_USER=sportsbet
      - MYSQL_PASSWORD=sportsbetpwd
      # - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
       - ./database:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci